In [4]:
!pip install spacy -qq
!python -m spacy download en_core_web_md -qq

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 49.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [6]:
import spacy
import numpy as np
import pandas as pd
import en_core_web_md

In [3]:
headlines = pd.read_csv('/content/abcnews-date-text.csv')
headlines

         publish_date                                      headline_text
0            20030219  aba decides against community broadcasting lic...
1            20030219     act fire witnesses must be aware of defamation
2            20030219     a g calls for infrastructure protection summit
3            20030219           air nz staff in aust strike for pay rise
4            20030219      air nz strike to affect australian travellers
...               ...                                                ...
1244179      20211231  two aged care residents die as state records 2...
1244180      20211231  victoria records 5;919 new cases and seven deaths
1244181      20211231    wa delays adopting new close contact definition
1244182      20211231  western ringtail possums found badly dehydrate...
1244183      20211231  what makes you a close covid contact here are ...

[1244184 rows x 2 columns]

In [10]:
pd.set_option('display.max_colwidth', None)

In [11]:
sample = headlines.sample(n=10)
sample

,publish_date,headline_text
1072158,20170302,gender pay gap improves slightly still outrageously high
613202,20110511,stitching up 4600 kms in a saddle for melanoma
414040,20080930,india stampede death toll rises to 144
1046838,20160907,tassal fish farm plans get some industry support
747476,20121210,murder accused pleads not guilty
855799,20140224,northern territory farm finance
742429,20121121,first asylum seekers arrive on manus island
1196974,20200429,afl geelong patrick dangerfield desperate for premiership win
102379,20040712,gaudio faces zabaleta in all argentine final
1227831,20210118,bottles thrown during melbourne derby w league match

In [12]:
nlp = en_core_web_md.load()

In [13]:
test_headlines = np.array(sample.get('headline_text'))

In [14]:
for doc in nlp.pipe(test_headlines):
    print([(ent.text, ent.label_) for ent in doc.ents])

[]
[('4600', 'CARDINAL')]
[('india', 'GPE'), ('144', 'CARDINAL')]
[]
[]
[]
[('first', 'ORDINAL'), ('manus island', 'LOC')]
[('afl geelong patrick dangerfield desperate', 'ORG')]
[('gaudio', 'PERSON'), ('zabaleta', 'ORG'), ('argentine', 'NORP')]
[('melbourne', 'GPE'), ('derby w league', 'ORG')]